### ISSUE TITLE
在volley里用的时候 一直报list.size = 0

### ISSUE THREAD

**Issue by LMJWEIJY** [baoyachi/StepView#15]
```
@DebugLog
    public void getStatus() {
        RequestQueue `requestQueue` = MyVolley.getRequestQueue();
        StringRequest request = new StringRequest(Request.Method.GET, AppConfig.SM_DD_STATUS + "/" + mId, new Response.Listener<String>() {
            @DebugLog
            @Override
            public void onResponse(String response) {
                if (!StringUtils.isEmpty(response))
                    setStepView(new Gson().fromJson(response, SmStatus[].class));
            }
        }, new Response.ErrorListener() {
            @DebugLog
            @Override
            public void onErrorResponse(VolleyError error) {

            }
        });
        requestQueue.add(request);
    }

    @DebugLog
    private void setStepView(SmStatus[] smStatuses) {
        List<String> statusString = new ArrayList<>();
       /* for (SmStatus status :
                smStatuses) {
            statusString.add(status.getStatusId() + "\n" + status.getStatusTime());
        }*/
//        mSmDdDetailStatusView.setStepViewTexts(statusString);
        setView();
    }
@DebugLog
    private void setView() {
        List<String> list0 = new ArrayList<>();
        list0.add("接已提交定案，等待系统确认");
        list0.add("您的商品需要从外地调拨，我们会尽快处理，请耐心等待");
        list0.add("您的订单已经进入亚洲第一仓储中心1号库准备出库");
        list0.add("您的订单预计6月23日送达您的手中，618期间促销火爆，可能影响送货时间，请您谅解，我们会第一时间送到您的手中");
        list0.add("您的订单已打印完毕");
        list0.add("您的订单已拣货完成");
        list0.add("扫描员已经扫描");
        list0.add("打包成功");
        list0.add("配送员【包牙齿】已出发，联系电话【130-0000-0000】，感谢您的耐心等待，参加评价还能赢取好多礼物哦");
        list0.add("感谢你在京东购物，欢迎你下次光临！");

     mSmDdDetailStatusView.setStepsViewIndicatorComplectingPosition(list0.size() - 2)//设置完成的步数
                .reverseDraw(false)//default is true
                .setStepViewTexts(list0)//总步骤
                .setLinePaddingProportion(0.85f)//设置indicator线与线间距的比例系数
                .setStepsViewIndicatorCompletedLineColor(ContextCompat.getColor(getActivity(), android.R.color.white))//设置StepsViewIndicator完成线的颜色
                .setStepsViewIndicatorUnCompletedLineColor(ContextCompat.getColor(getActivity(), R.color.uncompleted_text_color))//设置StepsViewIndicator未完成线的颜色
                .setStepViewComplectedTextColor(ContextCompat.getColor(getActivity(), android.R.color.white))//设置StepsView text完成线的颜色
                .setStepViewUnComplectedTextColor(ContextCompat.getColor(getActivity(), R.color.uncompleted_text_color))//设置StepsView text未完成线的颜色
                .setStepsViewIndicatorCompleteIcon(ContextCompat.getDrawable(getActivity(), R.drawable.complted))//设置StepsViewIndicator CompleteIcon
                .setStepsViewIndicatorDefaultIcon(ContextCompat.getDrawable(getActivity(), R.drawable.default_icon))//设置StepsViewIndicator DefaultIcon
                .setStepsViewIndicatorAttentionIcon(ContextCompat.getDrawable(getActivity(), R.drawable.attention));//设置StepsViewIndicator AttentionIcon
    }
}

```

6:30:47.364 4157-4157/com.dijiaapp.eat.atext E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.dijiaapp.eat.atext, PID: 4157
                                                                      java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                          at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                          at java.util.ArrayList.get(ArrayList.java:308)
                                                                          at com.baoyachi.stepview.VerticalStepView.ondrawIndicator(VerticalStepView.java:203)
                                                                          at com.baoyachi.stepview.VerticalStepViewIndicator.onDraw(VerticalStepViewIndicator.java:193)
                                                                          at android.view.View.draw(View.java:15278)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14214)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:14174)
                                                                          at android.view.View.getDisplayList(View.java:14236)
                                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
                                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
                                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2570)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2393)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2023)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1102)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5930)
                                                                      	at and

**Comment by LMJWEIJY** [comment]
上面是我的代码，下面是报的错，直接调用事例代码 就会报错。

**Comment by baoyachi** [comment]
恩，请问怎么能联系你，想详细看看问题原因？

**Comment by LMJWEIJY** [comment]
qq? 1289120516

**Comment by baoyachi** [comment]
@LMJWEIJY 之前有一哥们遇到这个问题，我想知道你那具体原因，好对其进行改正！

**Comment by LMJWEIJY** [comment]
@baoyachi 你加我Q?

**Comment by baoyachi** [comment]
hi ,it's been fixed！
you can see here[tag1.7](https://github.com/baoyachi/StepView/releases/tag/1.7).
Now，you can just update you gradle version with

```java
compile 'com.github.baoyachi:StepView:1.7'
```
Thank you very much!O(∩_∩)O
👍

**Comment by baoyachi** [comment]
@LMJWEIJY 

 hi ,it's been fixed！
you can see here [tag1.7](https://github.com/baoyachi/StepView/releases/tag/1.7).
Now，you can just update you gradle version with

```java
compile 'com.github.baoyachi:StepView:1.7'
```
Thank you very much!O(∩_∩)O
👍
